# Generated by Django 3.2.18 on 2023-03-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_auto_20230321_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dp',
        ),
    ]
