# Generated by Django 3.2.18 on 2023-03-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dp',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dp',
            name='last_name',
        ),
    ]
