# Generated by Django 3.2.18 on 2023-03-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0005_auto_20230322_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='display_image',
            field=models.ImageField(blank=True, default='media/avi.png', help_text='Optional', null=True, upload_to='media/courseimage'),
        ),
    ]
