# Generated by Django 3.2.18 on 2023-03-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0006_alter_course_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='targets',
        ),
        migrations.AddField(
            model_name='course',
            name='descrption',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
