# Generated by Django 3.2.18 on 2023-03-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0008_alter_course_descrption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, upload_to='media/coursevideo'),
        ),
    ]
