# Generated by Django 3.2.18 on 2023-03-24 22:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0009_alter_coursecontent_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
