# Generated by Django 3.2.18 on 2023-03-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0015_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
