# Generated by Django 3.2.18 on 2023-04-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0017_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('testimonial', models.TextField()),
                ('image', models.ImageField(upload_to='media/testimonials')),
                ('bio', models.CharField(max_length=300)),
            ],
        ),
    ]
