# Generated by Django 3.2.18 on 2023-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0018_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discounted_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
