# Generated by Django 3.2.18 on 2023-04-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0021_auto_20230419_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
